name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4']

    name: Tests (PHP ${{ matrix.php }})
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug
        extensions: pdo_sqlite

    - name: Install Dependencies
      uses: ramsey/composer-install@v3
      with:
          dependency-versions: "highest"

    - name: Run Tests
      run: |
        mkdir -p build/logs
        vendor/bin/phpunit --coverage-clover build/logs/clover.xml

    - name: Downloading Scrutinizer CI binary
      run: wget https://scrutinizer-ci.com/ocular.phar

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: Uploading code coverage to Scrutinizer CI
      run: php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

